---
apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: authentik-database
  labels:
    app.kubernetes.io/component: 'database'
spec:
  inheritedMetadata:
    labels:
      app.kubernetes.io/component: 'database'
    annotations:
      reloader.stakater.com/search: 'false'  # Enables search mode (only reloads if matching secrets/configMaps are found)
  instances: 0
  bootstrap:
    initdb:
      database: authentik
      owner: authentik
      secret:
        name: authentik-database-user
      dataChecksums: true  # When dataChecksums is set to true, CloudNativePG invokes the -k option in initdb to enable checksums on data pages and help detect corruption by the I/O system - that would otherwise be silent (default: false).
      encoding: UTF8  # When encoding set to a value, CloudNativePG passes it to the --encoding option in initdb, which selects the encoding of the template database (default: UTF8).
      locale: C.UTF-8  # When locale is set to a value, CloudNativePG passes it to the --locale option in initdb. This option controls the locale, as defined in "Locale Support" from the PostgreSQL documentation. By default, the locale parameter is empty. In this case, environment variables such as LANG are used to determine the locale. Be aware that these variables can vary between container images, potentially leading to inconsistent behavior.
      localeCollate: C.UTF-8  # When localeCollate is set to a value, CloudNativePG passes it to the --lc-collate option in initdb. This option controls the collation order (LC_COLLATE subcategory), as defined in "Locale Support" from the PostgreSQL documentation (default: C).
      localeCType: C.UTF-8  # When localeCType is set to a value, CloudNativePG passes it to the --lc-ctype option in initdb. This option controls the collation order (LC_CTYPE subcategory), as defined in "Locale Support" from the PostgreSQL documentation (default: C).
      localeProvider: libc  # When localeProvider is set to a value, CloudNativePG passes it to the --locale-provider option in initdb. This option controls the locale provider, as defined in "Locale Support" from the PostgreSQL documentation (default: empty, which means libc for PostgreSQL). Available from PostgreSQL 15.
      postInitApplicationSQL:
        - "REVOKE CONNECT ON DATABASE postgres FROM PUBLIC;"
        - "GRANT CONNECT ON DATABASE postgres TO postgres;"
        - "GRANT CONNECT ON DATABASE postgres TO streaming_replica;"
        - "REVOKE CONNECT ON DATABASE authentik FROM PUBLIC;"
        - "GRANT CONNECT ON DATABASE authentik TO authentik;"
  imageCatalogRef:
    apiGroup: postgresql.cnpg.io
    kind: ClusterImageCatalog
    name: postgresql-minimal-trixie
    major: 0
  storage:
    size: 0Gi
    storageClass: local-path
  postgresql:
    parameters:
      shared_buffers: "128MB"  # Sets the amount of memory the database server uses for shared memory buffers. 25% of system memory is a good starting value.
      max_connections: "500"
    synchronous:
      method: any
      number: 1
      dataDurability: required
  resources:
    requests:
      memory: 512Mi
      cpu: 0.5
    limits:
      memory: 512Mi
      cpu: 1.0
  plugins:
    - name: barman-cloud.cloudnative-pg.io
      isWALArchiver: true
      parameters:
        barmanObjectName: authentik-database-objectstore
