---
apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component

configMapGenerator:
  - name: alloy-logs-events-config
    behavior: create
    options:
      labels:
        app.kubernetes.io/component: alloy
      annotations:
        reloader.stakater.com/match: 'false'
    files:
      - 40-logs-events.alloy=./configs/40-logs-events.alloy

patches:
  - path: ./patches/statefulset.yaml
    target:
      group: apps
      version: v1
      kind: StatefulSet
      name: alloy-metrics
