apiVersion: postgresql.cnpg.io/v1
kind: ScheduledBackup
metadata:
  name: homeassistant-db-scheduledbackup
spec:
  immediate: true
  schedule: "0 0 0 * * *"
  backupOwnerReference: self
  method: plugin
  pluginConfiguration:
      name: barman-cloud.cloudnative-pg.io
  cluster:
    name: homeassistant-db