---
apiVersion: builtin
kind: ReplicaCountTransformer
metadata:
  name: nse-body-analytics-replicatransformer
replica:
  name: nse-body-analytics
  count: 1
fieldSpecs:
  - path: spec/replicas
    create: true
    kind: Deployment
  - path: spec/replicas
    create: true
    kind: ReplicationController
  - path: spec/replicas
    create: true
    kind: ReplicaSet
  - path: spec/replicas
    create: true
    kind: StatefulSet
