---
apiVersion: builtin
kind: ConfigMapGenerator
metadata:
  name: pihole-conditional-forwarders
behavior: create
options:
  labels:
    app.kubernetes.io/component: 'application'  # The component within the architecture
files:
  - ./configs/01-custom-forwarders.conf
