---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ./resources/namespace.yaml
  - ./resources/network-policy-clients-to-forgejo-ssh.yaml
  - ./resources/network-policy-runner-to-forgejo.yaml
  - ./resources/network-policy-traefik-to-forgejo.yaml
  - ./resources/resource-quota.yaml

components:
  - ../components/_forgejo
  - ../components/_runner
