apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

sortOptions:
  # If not specified, HelmChart will be deployed before HelmChartConfig - This can lead to unconfigured HelmChart deployments
  order: fifo

buildMetadata:
  - managedByLabel
  - originAnnotations
  # - transformerAnnotations

labels:
  - includeSelectors: false
    pairs:
      app.kubernetes.io/component: certificates
      app.kubernetes.io/instance: trust-manager
      app.kubernetes.io/name: trust-manager
      app.kubernetes.io/part-of: system-services

resources:
  - ../../base

patches:
  # https://github.com/cert-manager/trust-manager/
  - path: ./patches/version.yaml
    target:
      group: helm.cattle.io
      version: v1
      kind: HelmChart
