---
apiVersion: helm.cattle.io/v1
kind: HelmChartConfig
metadata:
  name: longhorn
spec:
  valuesContent: >-
    persistence:
      defaultClass: false
      defaultFsType: ext4
      defaultClassReplicaCount: ###NUMBER_OF_STORAGE_REPLICAS(3)###
      defaultDataLocality: 'best-effort'
      defaultReplicaAutoBalance: 'best-effort'
      reclaimPolicy: 'Delete'
      migratable: false
      removeSnapshotsDuringFilesystemTrim: 'ignored'
    csi:
      attacherReplicaCount: ###NUMBER_OF_REPLICAS(2)###
      provisionerReplicaCount: ###NUMBER_OF_REPLICAS(2)###
      resizerReplicaCount: ###NUMBER_OF_REPLICAS(1)###
      snapshotterReplicaCount: ###NUMBER_OF_REPLICAS(1)###
    defaultSettings:
      storageOverProvisioningPercentage: '100'
      storageMinimalAvailablePercentage: '10'
      storageReservedPercentageForDefaultDisk: '10'
      replicaSoftAntiAffinity: false
      allowVolumeCreationWithDegradedAvailability: false
      defaultDataLocality: 'best-effort'
      defaultReplicaCount: '###NUMBER_OF_REPLICAS(3)###'
      deletingConfirmationFlag: false
      upgradeChecker: true
      allowCollectingLonghornUsageMetrics: false
      replicaAutoBalance: 'best-effort'
      concurrentAutomaticEngineUpgradePerNodeLimit: '3'
      snapshotMaxCount: '60'
    defaultBackupStore:
      backupTarget: '###AZURE_BLOB_STORAGE_URL###'
      backupTargetCredentialSecret: 'longhorn-backup-secret-azure'
      pollInterval: 0
    longhornUI:
      replicas: ###NUMBER_OF_REPLICAS(1)###
    longhornConversionWebhook:
      replicas: ###NUMBER_OF_REPLICAS(2)###
    longhornAdmissionWebhook:
      replicas: ###NUMBER_OF_REPLICAS(2)###
    longhornRecoveryBackend:
      replicas: ###NUMBER_OF_REPLICAS(1)###
