# yaml-language-server: $schema=https://json.schemastore.org/kustomize-patches-6902.json
# RFC 6902 JSON Patch for setting daily trim job schedule
- op: replace
  path: /spec/cron
  value: "###CRON_STYLE_SCHEDULE###"
