# yaml-language-server: $schema=https://json.schemastore.org/kustomize-patches-6902.json
# RFC 6902 JSON Patch for setting StorageClass configuration
- op: replace
  path: /parameters/numberOfReplicas
  value: "###NUMBER_OF_STORAGE_REPLICAS###"
