---
apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component

configMapGenerator:
  - name: alloy-unpoller-telemetry
    behavior: create
    options:
      labels:
        app.kubernetes.io/component: alloy
      annotations:
        reloader.stakater.com/match: 'false'
    files:
      - 65-unpoller-telemetry.alloy=./configs/65-unpoller-telemetry.alloy
