---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: homeassistant

buildMetadata:
  - managedByLabel
  - originAnnotations
  # - transformerAnnotations

labels:
  - includeSelectors: false
    pairs:
      app.kubernetes.io/version: 2026.7.2 # The current version of the application

resources:
  - ../../base

generators:
  - ./generators/secret-editor-user.yaml
  - ./generators/secret-historydb-grafana-auth.yaml
  - ./generators/secret-mqtt-acl.yaml
  - ./generators/secret-mqtt-user.yaml

patches:
  - path: ./patches/certificate-editor.yaml
    target:
      group: cert-manager.io
      version: v1
      kind: Certificate
      name: editor
  - path: ./patches/certificate-homeassistant.yaml
    target:
      group: cert-manager.io
      version: v1
      kind: Certificate
      name: homeassistant
  - path: ./patches/certificate-historydb.yaml
    target:
      group: cert-manager.io
      version: v1
      kind: Certificate
      name: historydb
  - path: ./patches/certificate-mqtt.yaml
    target:
      group: cert-manager.io
      version: v1
      kind: Certificate
      name: mqtt
  - path: ./patches/ingressroute-editor.yaml
    target:
      group: traefik.io
      version: v1alpha1
      kind: IngressRoute
      name: editor
  - path: ./patches/ingressroute-homeassistant.yaml
    target:
      group: traefik.io
      version: v1alpha1
      kind: IngressRoute
      name: homeassistant
  - path: ./patches/ingressroute-historydb.yaml
    target:
      group: traefik.io
      version: v1alpha1
      kind: IngressRoute
      name: historydb
  - path: ./patches/multus-homeassistant.yaml
    target:
      group: k8s.cni.cncf.io
      version: v1
      kind: NetworkAttachmentDefinition
      name: homeassistant
  - path: ./patches/pvc-editor.yaml
    target:
      group: apps
      version: v1
      kind: StatefulSet
      name: editor
  - path: ./patches/pvc-homeassistant.yaml
    target:
      group: apps
      version: v1
      kind: StatefulSet
      name: homeassistant
  - path: ./patches/pvc-historydb.yaml
    target:
      group: apps
      version: v1
      kind: StatefulSet
      name: historydb
  - path: ./patches/resource-quota.yaml
    target:
      version: v1
      kind: ResourceQuota
  - path: ./patches/service-mqtt.yaml
    target:
      version: v1
      kind: Service
      name: mqtt
  - path: ./patches/statefulset-historydb.yaml
    target:
      group: apps
      version: v1
      kind: StatefulSet
      name: historydb

transformers:
  # https://hub.docker.com/_/busybox
  # https://hub.docker.com/_/eclipse-mosquitto
  # https://github.com/linuxserver/docker-code-server
  # https://github.com/home-assistant/core
  # https://github.com/VictoriaMetrics/VictoriaMetrics
  - ./transformers/images.yaml
  - ./transformers/labels.yaml
  - ./transformers/replicas.yaml
