# =================================================================
# General configuration
# =================================================================
per_listener_settings false
allow_zero_length_clientid false
max_inflight_messages 20
max_queued_messages 1000
max_packet_size 1048576
persistent_client_expiration 1h
user mosquitto

# =================================================================
# Listeners
# =================================================================
# Listener Unencrypted for legacy devices
listener 1883
socket_domain ipv4
max_connections 250
protocol mqtt
use_username_as_clientid false

# Listener Encrypted listener for secure clients
listener 8883
socket_domain ipv4
max_connections 250
protocol mqtt
use_identity_as_username false
certfile /mosquitto/certs/tls.crt
keyfile /mosquitto/certs/tls.key
require_certificate false

# =================================================================
# Persistence
# =================================================================
autosave_interval 300
autosave_on_changes false
persistence true
persistence_file mosquitto.db
persistence_location /mosquitto/data

# =================================================================
# Logging
# =================================================================
log_dest stdout
log_type error
log_type warning
log_type notice
log_type information
log_type subscribe
log_type unsubscribe
connection_messages true
log_timestamp true
log_timestamp_format %Y-%m-%dT%H:%M:%S

# =================================================================
# Security
# =================================================================
allow_anonymous false
password_file /mosquitto/config/passwd
acl_file /mosquitto/config/acl
