---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: pihole-to-application
spec:
  podSelector:
    matchLabels:
      app.kubernetes.io/component: application
  policyTypes:
    - Ingress
  ingress:
    - from:
        - namespaceSelector:
            matchLabels:
              kubernetes.io/metadata.name: pihole
        - podSelector:
            matchLabels:
              app.kubernetes.io/name: pihole
      ports:
        - protocol: TCP
          port: 53
        - protocol: UDP
          port: 53
