---
apiVersion: v1
kind: Service
metadata:
  name: grafana-renderer
  labels:
    app.kubernetes.io/component: 'renderer'
spec:
  selector:
    app.kubernetes.io/component: 'renderer'
  ports:
    - protocol: TCP
      port: 8081
      targetPort: 8081
      name: http
  type: ClusterIP
