---
apiVersion: builtin
kind: LabelTransformer
metadata:
  name: authentik-label-transformer
labels:
  app.kubernetes.io/name: authentik               # The name of the application
  app.kubernetes.io/instance: authentik    # A unique name identifying the instance of an application
  app.kubernetes.io/part-of: authentik            # The name of a higher level application this one is part of
  app.kubernetes.io/version: 2025.10.1            # The current version of the application
fieldSpecs:
  - path: metadata/labels
    create: true
  - path: spec/secretTemplate/labels
    create: true
    kind: Certificate
  - path: spec/inheritedMetadata/labels
    create: true
    kind: Cluster
  - path: spec/selector/matchLabels
    create: true
    kind: Deployment
  - path: spec/template/metadata/labels
    create: true
    kind: Deployment
  - path: spec/selector
    create: true
    kind: Service
  - path: spec/selector/matchLabels
    create: true
    kind: StatefulSet
  - path: spec/template/metadata/labels
    create: true
    kind: StatefulSet
  - path: spec/volumeClaimTemplates/metadata/labels
    create: true
    kind: StatefulSet
