apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: scrypted

buildMetadata:
  - managedByLabel
  - originAnnotations
  #- transformerAnnotations

labels:
  - includeSelectors: false
    pairs:
      app.kubernetes.io/version: v0.139.0-noble-full # The current version of the application

resources:
  - ../../base

patches:
  - path: ./patches/certificate.json
    target:
      group: cert-manager.io
      version: v1
      kind: Certificate
  - path: ./patches/ingressroute.json
    target:
      group: traefik.io
      version: v1alpha1
      kind: IngressRoute
  - path: ./patches/multus.yaml
    target:
      group: k8s.cni.cncf.io
      version: v1
      kind: NetworkAttachmentDefinition
  - path: ./patches/resource-quota.json
    target:
      version: v1
      kind: ResourceQuota

transformers:
  # https://github.com/koush/scrypted
  - ./transformers/images.yaml
  - ./transformers/labels.yaml
  - ./transformers/replicas.yaml
