apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ./resources/certificate.yaml
  - ./resources/ingressroute.yaml
  - ./resources/multus.yaml
  - ./resources/namespace.yaml
  - ./resources/network-policy.yaml
  - ./resources/resource-quota.yaml
  - ./resources/service.yaml
  - ./resources/statefulset.yaml

patches:
  - path: ./patches/config.yaml
    target:
      group: apps
      version: v1
      kind: StatefulSet
      name: pihole
