---
apiVersion: builtin
kind: SecretGenerator
metadata:
  name: nebula-sync-replicas
behavior: create
options:
  labels:
    app.kubernetes.io/component: 'application'
type: Opaque
envs:
  # For hashed passwords, use the following format:
  # echo -n "YourPassword" | sha256sum | awk '{printf "%s",$1}' | sha256sum | awk '{printf "%s",$1}'
  - ./secrets/secret-nebula-sync-replicas.env
