apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: unbound

buildMetadata:
  - managedByLabel
  - originAnnotations
  #- transformerAnnotations

labels:
  - includeSelectors: false
    pairs:
      app.kubernetes.io/version: 1.22.0 # The current version of the application

resources:
  - ../../base

generators:
  - ./generators/configs.yaml

patches:
  - path: ./patches/resource-quota.json
    target:
      version: v1
      kind: ResourceQuota

transformers:
  # https://github.com/MatthewVance/unbound-docker/
  - ./transformers/images.yaml
  - ./transformers/labels.yaml
  - ./transformers/replicas.yaml
