---
apiVersion: builtin
kind: SecretGenerator
metadata:
  name: barman-objectstore-default-credentials
behavior: create
options:
  disableNameSuffixHash: true
envs:
  - ./secrets/barman-objectstore-default-credentials.txt
