---
apiVersion: builtin
kind: ReplicaCountTransformer
metadata:
  name: uptimekuma-replicatransformer
replica:
  name: uptimekuma
  count: ###NUMBER_OF_REPLICAS(1)###
fieldSpecs:
  - path: spec/replicas
    create: false
    kind: Deployment
  - path: spec/replicas
    create: false
    kind: ReplicationController
  - path: spec/replicas
    create: false
    kind: ReplicaSet
  - path: spec/replicas
    create: true
    kind: StatefulSet
---
apiVersion: builtin
kind: ReplicaCountTransformer
metadata:
  name: uptimekuma-database-replicatransformer
replica:
  name: uptimekuma-database
  count: ###NUMBER_OF_REPLICAS(1)###
fieldSpecs:
  - path: spec/replicas
    create: false
    kind: Deployment
  - path: spec/replicas
    create: false
    kind: ReplicationController
  - path: spec/replicas
    create: false
    kind: ReplicaSet
  - path: spec/replicas
    create: true
    kind: StatefulSet
