---
apiVersion: builtin
kind: ReplicaCountTransformer
metadata:
  name: uptimekuma-replicatransformer
replica:
  name: uptimekuma
  count: 1
fieldSpecs:
  - path: spec/replicas
    create: true
    kind: Deployment
  - path: spec/replicas
    create: true
    kind: ReplicationController
  - path: spec/replicas
    create: true
    kind: ReplicaSet
  - path: spec/replicas
    create: true
    kind: StatefulSet
    
---
apiVersion: builtin
kind: ReplicaCountTransformer
metadata:
  name: uptimekuma-database-replicatransformer
replica:
  name: uptimekuma-database
  count: 1
fieldSpecs:
  - path: spec/replicas
    create: true
    kind: Deployment
  - path: spec/replicas
    create: true
    kind: ReplicationController
  - path: spec/replicas
    create: true
    kind: ReplicaSet
  - path: spec/replicas
    create: true
    kind: StatefulSet
