---
apiVersion: builtin
kind: ImageTagTransformer
metadata:
  name: timeserver-imagetransformer
imageTag:
  name: ghcr.io/aessing/chronyd
  newTag: 1.4.4
  
---
apiVersion: builtin
kind: ImageTagTransformer
metadata:
  name: busybox-imagetransformer
imageTag:
  name: busybox
  newTag: 1.37.0
