---
apiVersion: builtin
kind: ImageTagTransformer
metadata:
  name: timeserver-imagetransformer
imageTag:
  name: ghcr.io/aessing/chronyd
  newTag: 1.4.7

---
apiVersion: builtin
kind: ImageTagTransformer
metadata:
  name: busybox-imagetransformer
imageTag:
  name: busybox
  newTag: 1.38.0
---
apiVersion: builtin
kind: ImageTagTransformer
metadata:
  name: chrony-metrics-imagetransformer
imageTag:
  name: quay.io/superq/chrony-exporter
  newTag: v0.14.0
