---
apiVersion: builtin
kind: ImageTagTransformer
metadata:
  name: grafana-haengine-imagetransformer
imageTag:
  name: redis
  newTag: 8.10.1
---
apiVersion: builtin
kind: ImageTagTransformer
metadata:
  name: grafana-renderer-imagetransformer
imageTag:
  name: grafana/grafana-image-renderer
  newTag: v5.12.2
---
apiVersion: builtin
kind: ImageTagTransformer
metadata:
  name: grafana-imagetransformer
imageTag:
  name: grafana/grafana
  newTag: 13.2.0-ubuntu
