---
apiVersion: builtin
kind: ImageTagTransformer
metadata:
  name: grafana-haengine-imagetransformer
imageTag:
  name: redis
  newTag: 8.4.0
---
apiVersion: builtin
kind: ImageTagTransformer
metadata:
  name: grafana-renderer-imagetransformer
imageTag:
  name: grafana/grafana-image-renderer
  newTag: v5.0.9
---
apiVersion: builtin
kind: ImageTagTransformer
metadata:
  name: grafana-imagetransformer
imageTag:
  name: grafana/grafana-oss
  newTag: 12.2.0-17142428006
