---
apiVersion: builtin
kind: ImageTagTransformer
metadata:
  name: grafana-database-imagetransformer
imageTag:
  name: mysql
  newTag: 9.4.0
---
apiVersion: builtin
kind: ImageTagTransformer
metadata:
  name: grafana-haengine-imagetransformer
imageTag:
  name: redis
  newTag: 8.0.3
---
apiVersion: builtin
kind: ImageTagTransformer
metadata:
  name: grafana-renderer-imagetransformer
imageTag:
  name: grafana/grafana-image-renderer
  newTag: 4.0.10
---
apiVersion: builtin
kind: ImageTagTransformer
metadata:
  name: grafana-imagetransformer
imageTag:
  name: grafana/grafana-oss
  newTag: 12.1.0
