---
apiVersion: builtin
kind: SecretGenerator
metadata:
  name: forgejo-runner-token
behavior: create
options:
  disableNameSuffixHash: true
  labels:
    app.kubernetes.io/component: 'runner'
  annotations:
    reloader.stakater.com/match: 'false'
type: Opaque
envs:
  - ./secrets/secret-forgejo-runner-token.env
