# Enable file descriptor and stat cache for local files
open_file_cache          max=1000 inactive=20s;
open_file_cache_valid    30s;
open_file_cache_min_uses 2;
open_file_cache_errors   on;

server {
    listen 8080;
    root /usr/share/nginx/html/assets;
    location / {
        autoindex off;
        expires 7d;
        add_header Cache-Control "public, max-age=604800, immutable";
    }
}