apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

labels:
  - includeSelectors: false
    pairs:
      app.kubernetes.io/component: 'dns'
  - includeSelectors: true
    pairs:
      app.kubernetes.io/name: 'bind'
      app.kubernetes.io/part-of: 'nameserver'

resources:
  - ./resources/certificate.yaml
  - ./resources/deployment.yaml
  - ./resources/namespace.yaml
  - ./resources/network-policy.yaml
  - ./resources/resource-quota.yaml
  - ./resources/service.yaml
