---
apiVersion: builtin
kind: ConfigMapGenerator
metadata:
  name: grafana-haengine-config
behavior: create
options:
  labels:
    app.kubernetes.io/component: 'haengine' # The component within the architecture
files:
  - ./configs/redis.conf
  - ./configs/redis-full.conf
