# yaml-language-server: $schema=https://json.schemastore.org/kustomize-patches-6902.json
# RFC 6902 JSON Patch for setting target namespace
- op: replace
  path: /spec/targetNamespace
  value: reloader-system
