---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ./resources/namespace.yaml
  - ./resources/network-policy-default-deny.yaml
  - ./resources/network-policy-allow-dns-egress.yaml
  - ./resources/network-policy-traefik-to-vmauth.yaml
  - ./resources/network-policy-vmauth-to-loki.yaml
  - ./resources/network-policy-vmauth-backend-egress.yaml
  - ./resources/resource-quota.yaml

components:
  - ../components/_application
  - ../components/_auth
  - ../components/_ingress
