---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: homeassistant-data
  labels:
    app.kubernetes.io/component: 'application'
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: longhorn-retain
  resources:
    requests:
      storage: 1Gi
