---
apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component

configMapGenerator:
  - name: alloy-central-telemetry
    behavior: create
    options:
      labels:
        app.kubernetes.io/component: alloy
      annotations:
        reloader.stakater.com/match: 'false'
    files:
      - 50-central-telemetry.alloy=./configs/50-central-telemetry.alloy

patches:
  - path: ./patches/statefulset.yaml
    target:
      group: apps
      version: v1
      kind: StatefulSet
      name: alloy
