---
apiVersion: v1
kind: Service
metadata:
  name: alloy-logs
  labels:
    app.kubernetes.io/component: alloy-logs
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/component: alloy-logs
  ports:
    - name: http
      protocol: TCP
      port: 12345
      targetPort: http
