---
apiVersion: builtin
kind: SecretGenerator
metadata:
  name: uptimekuma-database-user
behavior: create
options:
  labels:
    app.kubernetes.io/component: 'database'
type: Opaque
envs:
  - ./secrets/secret-uptimekuma-database-user.env
