---
apiVersion: builtin
kind: PatchTransformer
metadata:
  name: patchtransformer-helmchartconfig
patch: |
  - op: replace
    path: /metadata/namespace
    value: "kube-system"
target:
  kind: HelmChartConfig
