---
apiVersion: builtin
kind: ConfigMapGenerator
metadata:
  name: homecdn-config
behavior: create
options:
  labels:
    app.kubernetes.io/component: 'application' # The component within the architecture
  annotations:
    # Reloads handled by kustomize with suffix
    reloader.stakater.com/match: 'false' # Marks the config/secret as eligible for reload in search mode
files:
  - ./configs/nginx.conf
  - ./configs/default.conf
