---
apiVersion: builtin
kind: ConfigMapGenerator
metadata:
  name: homecdn-config
behavior: create
options:
  labels:
    app.kubernetes.io/component: 'application' # The component within the architecture
files:
  - ./configs/nginx.conf
  - ./configs/default.conf
