---
apiVersion: builtin
kind: ImageTagTransformer
metadata:
  name: alloy-image-transformer
imageTag:
  name: grafana/alloy
  newTag: v1.19.2

---
apiVersion: builtin
kind: ImageTagTransformer
metadata:
  name: node-exporter-image-transformer
imageTag:
  name: quay.io/prometheus/node-exporter
  newTag: v1.12.1

---
apiVersion: builtin
kind: ImageTagTransformer
metadata:
  name: kube-state-metrics-image-transformer
imageTag:
  name: registry.k8s.io/kube-state-metrics/kube-state-metrics
  newTag: v2.20.0
