---
apiVersion: builtin
kind: ImageTagTransformer
metadata:
  name: scrypted-imagetransformer
imageTag:
  name: ghcr.io/koush/scrypted
  newTag: v0.142.7-noble-full
---
apiVersion: builtin
kind: ImageTagTransformer
metadata:
  name: busybox-imagetransformer
imageTag:
  name: busybox
  newTag: 1.37.0
