---
apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component

configMapGenerator:
  - name: nameserver-config
    behavior: create
    options:
      labels:
        app.kubernetes.io/component: 'application'  # The component within the architecture
      annotations:
        # Reloads handled by kustomize with suffix
        reloader.stakater.com/match: 'false'  # Marks the config/secret as eligible for reload in search mode
    files:
      - named.conf
