apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component

configMapGenerator:
  - name: nameserver-config
    behavior: create
    options:
      labels:
        app.kubernetes.io/component: 'application' # The component within the architecture
    files:
      - named.conf
