---
apiVersion: v1
kind: Service
metadata:
  name: unpoller
  labels:
    app.kubernetes.io/component: application
spec:
  selector:
    app.kubernetes.io/component: application
  ports:
    - name: metrics
      protocol: TCP
      port: 9130
      targetPort: metrics
  type: ClusterIP
