apiVersion: v1
kind: Secret
metadata:
  name: cnpg-controller-manager-config
type: Opaque
stringData:
  CLUSTERS_ROLLOUT_DELAY: '60'
  INSTANCES_ROLLOUT_DELAY: '10'
  KUBERNETES_CLUSTER_DOMAIN: '###CLUSTER_DOMAIN###'