---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: editor
  labels:
    app.kubernetes.io/component: 'editor'
  annotations:
    reloader.stakater.com/search: 'false' # Enables search mode (only reloads if matching secrets/configMaps are found)
spec:
  revisionHistoryLimit: 3
  serviceName: editor
  selector:
    matchLabels:
      app.kubernetes.io/component: 'editor'
  replicas: 0
  persistentVolumeClaimRetentionPolicy:
    whenScaled: Retain
    whenDeleted: Retain
  updateStrategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
  template:
    metadata:
      labels:
        app.kubernetes.io/component: 'editor'
    spec:
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
      containers:
        - name: editor
          image: lscr.io/linuxserver/code-server:0.0.0
          imagePullPolicy: IfNotPresent
          securityContext:
            runAsNonRoot: false
            allowPrivilegeEscalation: false
            capabilities:
              drop:
                - ALL
              add:
                - CHOWN
                - DAC_OVERRIDE
                - DAC_READ_SEARCH
                - FOWNER
                - SETGID
                - SETUID
            seccompProfile:
              type: RuntimeDefault
            readOnlyRootFilesystem: false
          resources:
            requests:
              cpu: 1
              memory: 1Gi
            limits:
              cpu: 2
              memory: 2Gi
          env:
            - name: DEFAULT_WORKSPACE
              value: /config/workspace
            - name: HASHED_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: editor-user
                  key: password
            - name: PUID
              value: '0'
            - name: PGID
              value: '0'
            - name: PWA_APPNAME
              value: 'Home Assistant Editor'
          ports:
            - containerPort: 8443
              protocol: TCP
              name: http
          startupProbe:
            httpGet:
              path: /
              port: http
              scheme: HTTP
            initialDelaySeconds: 5
            periodSeconds: 5
            timeoutSeconds: 2
            successThreshold: 1
            failureThreshold: 30
          readinessProbe:
            httpGet:
              path: /
              port: http
              scheme: HTTP
            initialDelaySeconds: 5
            periodSeconds: 5
            timeoutSeconds: 2
            successThreshold: 1
            failureThreshold: 3
          livenessProbe:
            httpGet:
              path: /
              port: http
              scheme: HTTP
            initialDelaySeconds: 30
            periodSeconds: 60
            timeoutSeconds: 2
            successThreshold: 1
            failureThreshold: 3
          volumeMounts:
            - mountPath: /config
              name: editor-config
            - mountPath: /config/workspace/code-server
              name: editor-config
            - mountPath: /config/workspace/homeassistant
              name: homeassistant-config-vol
      volumes:
        - name: homeassistant-config-vol
          persistentVolumeClaim:
            claimName: homeassistant-config-homeassistant-0
  volumeClaimTemplates:
    - metadata:
        name: editor-config
        labels:
          app.kubernetes.io/component: 'editor'
      spec:
        accessModes:
          - ReadWriteOnce
        storageClassName: longhorn-retain
        resources:
          requests:
            storage: 0Gi
