---
apiVersion: barmancloud.cnpg.io/v1
kind: ObjectStore
metadata:
  name: postgres-database-objectstore
  labels:
    app.kubernetes.io/component: 'database'
spec:
  configuration:
    destinationPath: s3://###BUCKET###/###FOLDER(CLUSTERNAME)###/
    endpointURL: https://###ENDPOINT_URL###
    s3Credentials:
      accessKeyId:
        name: postgres-database-objectstore
        key: ACCESS_KEY_ID
      secretAccessKey:
        name: postgres-database-objectstore
        key: ACCESS_SECRET_KEY
    data:
      compression: gzip
    wal:
      compression: zstd
  retentionPolicy: 30d
