---
apiVersion: builtin
kind: ConfigMapGenerator
metadata:
  name: fortnitestats-player
behavior: create
options:
  labels:
    app.kubernetes.io/component: 'application'
type: Opaque
files:
  - ./configs/player.txt
