---
apiVersion: builtin
kind: ImageTagTransformer
metadata:
  name: busybox-imagetransformer
imageTag:
  name: busybox
  newTag: 1.37.0
---
apiVersion: builtin
kind: ImageTagTransformer
metadata:
  name: mqtt-imagetransformer
imageTag:
  name: eclipse-mosquitto
  newTag: 2.0.21
---
apiVersion: builtin
kind: ImageTagTransformer
metadata:
  name: recorder-imagetransformer
imageTag:
  name: mariadb
  newTag: 11.7.2
