---
apiVersion: builtin
kind: ImageTagTransformer
metadata:
  name: busybox-imagetransformer
imageTag:
  name: busybox
  newTag: 1.37.0
---
apiVersion: builtin
kind: ImageTagTransformer
metadata:
  name: editor-imagetransformer
imageTag:
  name: lscr.io/linuxserver/code-server
  newTag: 4.102.3
---
apiVersion: builtin
kind: ImageTagTransformer
metadata:
  name: homeassistant-imagetransformer
imageTag:
  name: ghcr.io/home-assistant/home-assistant
  newTag: 2025.8.1
---
apiVersion: builtin
kind: ImageTagTransformer
metadata:
  name: mqtt-imagetransformer
imageTag:
  name: eclipse-mosquitto
  newTag: 2.0.22
---
apiVersion: builtin
kind: ImageTagTransformer
metadata:
  name: recorder-imagetransformer
imageTag:
  name: mariadb
  newTag: 11.8.2
