---
apiVersion: builtin
kind: ImageTagTransformer
metadata:
  name: busybox-imagetransformer
imageTag:
  name: busybox
  newTag: 1.37.0
---
apiVersion: builtin
kind: ImageTagTransformer
metadata:
  name: editor-imagetransformer
imageTag:
  name: lscr.io/linuxserver/code-server
  newTag: 4.106.2-ls306
---
apiVersion: builtin
kind: ImageTagTransformer
metadata:
  name: homeassistant-imagetransformer
imageTag:
  name: ghcr.io/home-assistant/home-assistant
  newTag: 2025.11.2
---
apiVersion: builtin
kind: ImageTagTransformer
metadata:
  name: mqtt-imagetransformer
imageTag:
  name: eclipse-mosquitto
  newTag: 2.0.22
