---
apiVersion: builtin
kind: ReplicaCountTransformer
metadata:
  name: editor-replicatransformer
replica:
  name: editor
  count: 1
fieldSpecs:
  - path: spec/replicas
    create: true
    kind: Deployment
  - path: spec/replicas
    create: true
    kind: ReplicationController
  - path: spec/replicas
    create: true
    kind: ReplicaSet
  - path: spec/replicas
    create: true
    kind: StatefulSet
---
apiVersion: builtin
kind: ReplicaCountTransformer
metadata:
  name: homeassistant-replicatransformer
replica:
  name: homeassistant
  count: 1
fieldSpecs:
  - path: spec/replicas
    create: true
    kind: Deployment
  - path: spec/replicas
    create: true
    kind: ReplicationController
  - path: spec/replicas
    create: true
    kind: ReplicaSet
  - path: spec/replicas
    create: true
    kind: StatefulSet
---
apiVersion: builtin
kind: ReplicaCountTransformer
metadata:
  name: mqtt-replicatransformer
replica:
  name: mqtt
  count: 1
fieldSpecs:
  - path: spec/replicas
    create: true
    kind: Deployment
  - path: spec/replicas
    create: true
    kind: ReplicationController
  - path: spec/replicas
    create: true
    kind: ReplicaSet
  - path: spec/replicas
    create: true
    kind: StatefulSet
---
apiVersion: builtin
kind: ReplicaCountTransformer
metadata:
  name: recorder-replicatransformer
replica:
  name: recorder
  count: 1
fieldSpecs:
  - path: spec/replicas
    create: true
    kind: Deployment
  - path: spec/replicas
    create: true
    kind: ReplicationController
  - path: spec/replicas
    create: true
    kind: ReplicaSet
  - path: spec/replicas
    create: true
    kind: StatefulSet
