---
- op: replace
  path: /spec/acme/email
  value: "###ADMIN_EMAIL_ADDRESS###"
- op: replace
  path: /spec/acme/solvers/0/dns01/azureDNS/clientID
  value: "###SERVICE_PRINCIPAL_CLIENT_ID###"
- op: replace
  path: /spec/acme/solvers/0/dns01/azureDNS/environment
  value: AzurePublicCloud
- op: replace
  path: /spec/acme/solvers/0/dns01/azureDNS/hostedZoneName
  value: "###FQDN_OF_DNS_ZONE###"
- op: replace
  path: /spec/acme/solvers/0/dns01/azureDNS/resourceGroupName
  value: "###AZURE_RESOURCE_GROUP_NAME###"
- op: replace
  path: /spec/acme/solvers/0/dns01/azureDNS/subscriptionID
  value: "###AZURE_SUBSCRIPTION_ID###"
- op: replace
  path: /spec/acme/solvers/0/dns01/azureDNS/tenantID
  value: "###AZURE_TENANT_ID###"
