apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ./resources/certificate.yaml
  - ./resources/deployment.yaml
  - ./resources/ingressroute.yaml
  - ./resources/namespace.yaml
  - ./resources/network-policy.yaml
  - ./resources/pvc.yaml
  - ./resources/resource-quota.yaml
  - ./resources/service.yaml

generators:
  - ./generators/config.yaml
