---
apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: ipallowlist-admin
  labels:
    kustomize-base: overlay
spec:
  ipAllowList:
    sourceRange:
      -  ###IP_ADRESS/CIDRANGE###
      -  ###IP_ADRESS/CIDRANGE###
      -  ###IP_ADRESS/CIDRANGE###

---
apiVersion: traefik.io/v1alpha1
kind: MiddlewareTCP
metadata:
  name: ipallowlist-admin
  labels:
    kustomize-base: overlay
spec:
  ipAllowList:
    sourceRange:
      -  ###IP_ADRESS/CIDRANGE###
      -  ###IP_ADRESS/CIDRANGE###
      -  ###IP_ADRESS/CIDRANGE###
