---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: authentik
  labels:
    app.kubernetes.io/component: 'server'
  annotations:
    kubernetes.io/ingress.class: traefik-external
spec:
  entryPoints:
    - websecure
  routes:
    - match: CHANGE_ME
      kind: Rule
      middlewares:
        - name: chain-default
          namespace: traefik-system
      services:
        - name: authentik-server
          port: 80
          sticky:
            cookie:
              httpOnly: true
              secure: true
              sameSite: none
  tls:
    secretName: authentik-certificate
