---
apiVersion: builtin
kind: SecretGenerator
metadata:
  name: nse-body-analytics-ghcr
behavior: create
options:
  labels:
    app.kubernetes.io/component: 'application'
type: kubernetes.io/dockerconfigjson
files:
  - .dockerconfigjson=./secrets/nse-body-analytics-ghcr.json
