---
apiVersion: builtin
kind: SecretGenerator
metadata:
  name: nse-body-analytics-secret
behavior: create
options:
  labels:
    app.kubernetes.io/component: 'application'
type: Opaque
envs:
  - ./secrets/nse-body-analytics-secret.env