---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mqtt
  labels:
    app.kubernetes.io/component: 'mqtt'
  annotations:
    #reloader.stakater.com/auto: 'true' # Reloads workload when any referenced ConfigMap or Secret changes
    reloader.stakater.com/search: 'true' # Enables search mode (only reloads if matching secrets/configMaps are found)
    #configmap.reloader.stakater.com/auto: 'true' # Reloads only when referenced ConfigMap(s) change
    #configmap.reloader.stakater.com/reload: '' # Reloads when specific ConfigMap(s) change, regardless of how they're used
    #secret.reloader.stakater.com/auto: 'true' # Reloads only when referenced Secret(s) change
    #secret.reloader.stakater.com/reload: '' # Reloads when specific Secret(s) change, regardless of how they're used
    reloader.stakater.com/rollout-strategy: 'rollout' # Specifies the rollout strategy for the workload (rollout (default) / restart)
spec:
  revisionHistoryLimit: 3
  replicas: 0
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 0
      maxUnavailable: 1
  template:
    metadata:
      labels:
        app.kubernetes.io/component: 'mqtt' # The component within the architecture
    spec:
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
      securityContext:
        fsGroup: 1883
      initContainers:
        - name: mqtt-init
          image: busybox:0.0.0
          command: [
              '/bin/sh',
              '-c',
              'mkdir -p /mosquitto/config;
              cp -f /mosquitto-temp/* /mosquitto/config/;
              chown 1883:1883 /mosquitto/config/*;
              chmod 440 /mosquitto/config/*;',
            ]
          volumeMounts:
            - name: mqtt-config-vol
              mountPath: /mosquitto-temp/mosquitto.conf
              subPath: mosquitto.conf
              readOnly: true
            - name: mqtt-acl-vol
              mountPath: /mosquitto-temp/acl
              subPath: acl
              readOnly: true
            - name: mqtt-user-vol
              mountPath: /mosquitto-temp/passwd
              subPath: passwd
              readOnly: true
            - name: mqtt-data-vol
              mountPath: '/mosquitto'
      containers:
        - name: mqtt
          image: eclipse-mosquitto:0.0.0
          imagePullPolicy: IfNotPresent
          securityContext:
            runAsNonRoot: true
            allowPrivilegeEscalation: false
            runAsUser: 1883
            runAsGroup: 1883
            capabilities:
              drop:
                - ALL
            seccompProfile:
              type: RuntimeDefault
            readOnlyRootFilesystem: true
          resources:
            requests:
              cpu: 0.01
              memory: 16Mi
            limits:
              cpu: 0.25
              memory: 32Mi
          ports:
            - containerPort: 1883
              protocol: TCP
              name: mqtt
            - containerPort: 8883
              protocol: TCP
              name: mqtt-tls
          startupProbe:
            tcpSocket:
              port: mqtt
            initialDelaySeconds: 5
            periodSeconds: 5
            timeoutSeconds: 2
            successThreshold: 1
            failureThreshold: 30
          readinessProbe:
            tcpSocket:
              port: mqtt
            initialDelaySeconds: 5
            periodSeconds: 5
            timeoutSeconds: 2
            successThreshold: 1
            failureThreshold: 3
          livenessProbe:
            tcpSocket:
              port: mqtt
            initialDelaySeconds: 30
            periodSeconds: 60
            timeoutSeconds: 2
            successThreshold: 1
            failureThreshold: 3
          volumeMounts:
            - name: mqtt-data-vol
              mountPath: '/mosquitto'
            - name: mqtt-certificate-vol
              mountPath: '/mosquitto/certs'
              readOnly: true
      volumes:
        - name: mqtt-config-vol
          configMap:
            name: mqtt-config
            defaultMode: 0440
        - name: mqtt-acl-vol
          secret:
            secretName: mqtt-acl
            defaultMode: 0440
        - name: mqtt-user-vol
          secret:
            secretName: mqtt-user
            defaultMode: 0440
        - name: mqtt-data-vol
          persistentVolumeClaim:
            claimName: mqtt-data
        - name: mqtt-certificate-vol
          secret:
            secretName: mqtt-certificate
