---
apiVersion: v1
kind: Service
metadata:
  name: mqtt
  labels:
    app.kubernetes.io/component: 'mqtt'
  annotations:
    metallb.io/loadBalancerIPs: 0.0.0.0
spec:
  selector:
    app.kubernetes.io/component: 'mqtt'
  ports:
    - protocol: TCP
      port: 1883
      targetPort: 1883
      name: mqtt
    - protocol: TCP
      port: 8883
      targetPort: 8883
      name: mqtt-tls
  type: LoadBalancer
