---
apiVersion: v1
kind: Service
metadata:
  name: grafana-oss-database
  labels:
    app.kubernetes.io/component: 'database'
spec:
  selector:
    app.kubernetes.io/component: 'database'
  clusterIP: None
  ports:
    - protocol: TCP
      port: 3306
      targetPort: 3306
      name: mysql
  type: ClusterIP
