---
apiVersion: batch/v1
kind: CronJob
metadata:
  name: fortnitestats
  labels:
    app.kubernetes.io/component: 'application'
  annotations:
    #reloader.stakater.com/auto: 'true' # Reloads workload when any referenced ConfigMap or Secret changes
    reloader.stakater.com/search: 'false' # Enables search mode (only reloads if matching secrets/configMaps are found)
    #configmap.reloader.stakater.com/auto: 'true' # Reloads only when referenced ConfigMap(s) change
    #configmap.reloader.stakater.com/reload: '' # Reloads when specific ConfigMap(s) change, regardless of how they're used
    #secret.reloader.stakater.com/auto: 'true' # Reloads only when referenced Secret(s) change
    #secret.reloader.stakater.com/reload: '' # Reloads when specific Secret(s) change, regardless of how they're used
    reloader.stakater.com/rollout-strategy: 'rollout' # Specifies the rollout strategy for the workload (rollout (default) / restart)
spec:
  successfulJobsHistoryLimit: 3
  failedJobsHistoryLimit: 3
  schedule: '*/5 * * * *' # every five minutes
  jobTemplate:
    spec:
      template:
        spec:
          securityContext:
            fsGroup: 1000
          containers:
            - name: fortnitestats
              image: ghcr.io/aessing/fortnitestats-2-influxdb:0.0.0
              imagePullPolicy: IfNotPresent
              securityContext:
                runAsNonRoot: true
                allowPrivilegeEscalation: false
                runAsUser: 1000
                runAsGroup: 1000
                capabilities:
                  drop:
                    - ALL
                  add:
                    - NET_RAW
                seccompProfile:
                  type: RuntimeDefault
                readOnlyRootFilesystem: true
              resources:
                requests:
                  cpu: 0.2
                  memory: 48Mi
                limits:
                  cpu: 0.5
                  memory: 128Mi
              env:
                - name: FORTNITE_API_TOKEN
                  valueFrom:
                    secretKeyRef:
                      name: fortnitestats-secrets
                      key: FORTNITE_API_TOKEN
                - name: INFLUXDB_URL
                  valueFrom:
                    secretKeyRef:
                      name: fortnitestats-secrets
                      key: INFLUXDB_URL
                - name: INFLUXDB_TOKEN
                  valueFrom:
                    secretKeyRef:
                      name: fortnitestats-secrets
                      key: INFLUXDB_TOKEN
                - name: INFLUXDB_ORG
                  valueFrom:
                    secretKeyRef:
                      name: fortnitestats-secrets
                      key: INFLUXDB_ORG
                - name: INFLUXDB_BUCKET
                  valueFrom:
                    secretKeyRef:
                      name: fortnitestats-secrets
                      key: INFLUXDB_BUCKET
              volumeMounts:
                - name: player-volume
                  mountPath: /app/player.txt
                  subPath: player.txt
          restartPolicy: OnFailure
          volumes:
            - name: player-volume
              configMap:
                name: fortnitestats-player
