---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: alloy-metrics
spec:
  template:
    spec:
      volumes:
        - name: config
          projected:
            sources:
              - configMap:
                  name: alloy-unifi-telemetry
