---
apiVersion: builtin
kind: ConfigMapGenerator
metadata:
  name: homepage-config
behavior: create
options:
  labels:
    app.kubernetes.io/component: 'application'  # The component within the architecture
files:
  - ./configs/bookmarks.yaml
  - ./configs/custom.css
  - ./configs/custom.js
  - ./configs/docker.yaml
  - ./configs/kubernetes.yaml
  - ./configs/services.yaml
  - ./configs/settings.yaml
  - ./configs/widgets.yaml
