---
apiVersion: builtin
kind: SecretGenerator
metadata:
  name: mailrise-users
behavior: create
options:
  labels:
    app.kubernetes.io/component: 'application'
type: Opaque
envs:
  - ./secrets/secret-mailrise-users.env
