---
apiVersion: builtin
kind: LabelTransformer
metadata:
  name: unpoller-label-transformer
labels:
  app.kubernetes.io/name: unpoller
  app.kubernetes.io/instance: unpoller-admin01
  app.kubernetes.io/part-of: monitoring
fieldSpecs:
  - path: metadata/labels
    create: true
  - path: spec/selector
    create: true
    kind: Service
  - path: spec/selector/matchLabels
    create: true
    kind: Deployment
  - path: spec/selector/matchLabels
    create: true
    kind: StatefulSet
  - path: spec/template/metadata/labels
    create: true
    kind: Deployment
  - path: spec/template/metadata/labels
    create: true
    kind: StatefulSet
  - path: spec/volumeClaimTemplates/metadata/labels
    create: true
    kind: StatefulSet
