apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ./resources/certificate.yaml
  - ./resources/cluster.yaml
  - ./resources/namespace.yaml
  - ./resources/network-policy-clients.yaml
  - ./resources/network-policy-cnpg.yaml
  - ./resources/network-policy-instance.yaml
  - ./resources/network-policy-kubeproxy.yaml
  - ./resources/object-store.yaml
  - ./resources/resource-quota.yaml
  - ./resources/scheduled-backup.yaml
