---
apiVersion: builtin
kind: ConfigMapGenerator
metadata:
  name: unbound-configs
behavior: create
options:
  labels:
    app.kubernetes.io/component: 'application' # The component within the architecture
files:
  - ./configs/unbound.conf
  - ./configs/a-records.conf
  - ./configs/forward-records.conf
  - ./configs/srv-records.conf
