---
apiVersion: builtin
kind: SecretGenerator
metadata:
  name: editor-user
behavior: create
options:
  labels:
    app.kubernetes.io/component: 'editor'
  annotations:
    # Reloads handled by kustomize with suffix
    reloader.stakater.com/match: 'false' # Marks the config/secret as eligible for reload in search mode
type: Opaque
envs:
  # https://github.com/coder/code-server/blob/main/docs/FAQ.md#can-i-store-my-password-hashed
  # echo -n "thisismypassword" | npx argon2-cli -e
  - ./secrets/secret-editor-user.env
