---
apiVersion: builtin
kind: SecretGenerator
metadata:
  name: mqtt-acl
behavior: create
options:
  labels:
    app.kubernetes.io/component: 'mqtt'
  annotations:
    # Reloads handled by kustomize with suffix
    reloader.stakater.com/match: 'false'  # Marks the config/secret as eligible for reload in search mode
type: Opaque
files:
  - acl=./secrets/secret-mqtt-acl.env
