---
apiVersion: builtin
kind: SecretGenerator
metadata:
  name: homeassistant-db-objectstore
behavior: create
options:
  disableNameSuffixHash: true
  labels:
    app.kubernetes.io/component: 'database'
    cnpg.io/reload: "true"
  annotations:
    # Reloads handled by kustomize with suffix
    reloader.stakater.com/match: 'false'  # Marks the config/secret as eligible for reload in search mode
type: Opaque
envs:
  - ./secrets/secret-homeassistant-db-objectstore.env
