---
apiVersion: builtin
kind: SecretGenerator
metadata:
  name: historydb-grafana-basicauth
behavior: create
options:
  disableNameSuffixHash: true
  labels:
    app.kubernetes.io/component: 'historydb'
type: kubernetes.io/basic-auth
envs:
  - ./secrets/secret-historydb-grafana-auth.env
