---
apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: chain-admin
spec:
  chain:
    middlewares:
      - name: forwarded-headers
        namespace: traefik-system
      - name: security-headers
        namespace: traefik-system
      - name: rate-limit
        namespace: traefik-system
      - name: ipallowlist-rfc1918
        namespace: traefik-system
      - name: compression
        namespace: traefik-system
