---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: timeserver
spec:
  policyTypes:
    - Ingress
  ingress:
    - from: [] # Allow from all sources
      ports:
        - protocol: UDP
          port: 123
