---
apiVersion: v1
kind: Service
metadata:
  name: timeserver
  annotations:
    metallb.universe.tf/loadBalancerIPs: '0.0.0.0'
spec:
  ports:
    - protocol: UDP
      port: 123
      targetPort: 123
      name: ntp
  type: LoadBalancer
