---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: fortnitestats

buildMetadata:
  - managedByLabel
  - originAnnotations
  # - transformerAnnotations

labels:
  - includeSelectors: false
    pairs:
      app.kubernetes.io/version: v0.3.4  # The current version of the application

resources:
  - ../../base

generators:
  - ./generators/config-player.yaml
  - ./generators/secret-fortnitestats.yaml

patches:
  - path: ./patches/resource-quota.yaml
    target:
      version: v1
      kind: ResourceQuota

transformers:
  # https://github.com/aessing/fortnite-stats-2-influx-container
  - ./transformers/images.yaml
  - ./transformers/labels.yaml
