---
apiVersion: builtin
kind: SecretGenerator
metadata:
  name: fortnitestats-secrets
behavior: create
options:
  labels:
    app.kubernetes.io/component: 'job'
type: Opaque
envs:
  - ./secrets/secret-fortnitestats.env
