---
apiVersion: builtin
kind: ConfigMapGenerator
metadata:
  name: vmauth-config
behavior: replace
options:
  labels:
    app.kubernetes.io/component: auth
  annotations:
    reloader.stakater.com/match: 'false'
files:
  - auth.yml=./configs/auth.yml
