---
apiVersion: builtin
kind: ConfigMapGenerator
metadata:
  name: loki-config
behavior: replace
options:
  labels:
    app.kubernetes.io/component: application
  annotations:
    reloader.stakater.com/match: 'false'
files:
  - loki.yaml=./configs/loki.yaml
