---
apiVersion: builtin
kind: SecretGenerator
metadata:
  name: monitoring-logs-auth
behavior: create
options:
  labels:
    app.kubernetes.io/component: auth
  annotations:
    # The generated name suffix triggers a vmauth rollout after rotation.
    reloader.stakater.com/match: 'false'
type: Opaque
envs:
  - ./secrets/secret-monitoring-logs-auth.env
