apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: uptimekuma

buildMetadata:
  - managedByLabel
  - originAnnotations
  - transformerAnnotations

labels:
  - includeSelectors: false
    pairs:
      app.kubernetes.io/version: '1.23.16'
  - includeSelectors: true
    pairs:
      app.kubernetes.io/instance: 'uptimekuma'

resources:
  - ../../base

patches:
  - path: ./patches/certificate.json
    target:
      group: cert-manager.io
      version: v1
      kind: Certificate
  - path: ./patches/ingressroute.json
    target:
      group: traefik.io
      version: v1alpha1
      kind: IngressRoute
  - path: ./patches/resource-quota.json
    target:
      version: v1
      kind: ResourceQuota

transformers:
  # https://github.com/louislam/uptime-kuma
  - ./transformers/images.yaml
  - ./transformers/replicas.yaml
