---
apiVersion: helm.cattle.io/v1
kind: HelmChartConfig
metadata:
  name: traefik
spec:
  valuesContent: >-
    deployment:
      enabled: true
      replicas: ###NUMBER_OF_REPLICAS(3)###
    ingressClass:
      enabled: true
      isDefaultClass: true
    ingressRoute:
      dashboard:
        enabled: false
    providers:
      kubernetesCRD:
        enabled: true
        ingressClass: traefik-external
        allowCrossNamespace: true
      kubernetesIngress:
        enabled: true
        publishedService:
          enabled: false
    log:
      level: INFO
    metrics:
      prometheus:
        addEntryPointsLabels: true
        addRoutersLabels: true
        addServicesLabels: true
    global:
      checkNewVersion: true
      sendAnonymousUsage: false
    additionalArguments:
      - '--serversTransport.insecureSkipVerify=true'
      - '--providers.kubernetesingress.ingressclass=traefik-external'
    ports:
      traefik:
        port: 9000
        expose:
          default: false
        exposedPort: 9000
        protocol: TCP
      web:
        port: 8000
        expose:
          default: true
        exposedPort: 80
        protocol: TCP
        http:
          redirections:
            entryPoint:
              to: websecure
              scheme: https
              permanent: true
      websecure:
        port: 8443
        expose:
          default: true
        exposedPort: 443
        protocol: TCP
        http3:
          enabled: false
        http:
          tls:
            enabled: true
      metrics:
        port: 9100
        expose:
          default: false
        exposedPort: 9100
    service:
      enabled: true
      type: LoadBalancer
      spec:
        externalTrafficPolicy: Local
        loadBalancerIP: '###IP_ADDRESS_FOR_TRAEFIK###'
    rbac:
      enabled: true
