users:
  - name: unifi-admin01-writer
    bearer_token: "%{UNIFI_ADMIN01_WRITER_TOKEN}"
    url_map:
      - src_paths:
          - "/api/v1/write"
        headers:
          - "Authorization:"
        url_prefix: "http://victoriametrics:8428/?extra_label=cluster=ADMIN01"
  - name: cluster-a-writer
    bearer_token: "%{WRITER_CLUSTER_A_TOKEN}"
    url_map:
      - src_paths:
          - "/api/v1/write"
        headers:
          - "Authorization:"
        url_prefix: "http://victoriametrics:8428/?extra_label=cluster=cluster-a"
  - name: cluster-b-writer
    bearer_token: "%{WRITER_CLUSTER_B_TOKEN}"
    url_map:
      - src_paths:
          - "/api/v1/write"
        headers:
          - "Authorization:"
        url_prefix: "http://victoriametrics:8428/?extra_label=cluster=cluster-b"
  - name: cluster-c-writer
    bearer_token: "%{WRITER_CLUSTER_C_TOKEN}"
    url_map:
      - src_paths:
          - "/api/v1/write"
        headers:
          - "Authorization:"
        url_prefix: "http://victoriametrics:8428/?extra_label=cluster=cluster-c"
  - name: cluster-d-writer
    bearer_token: "%{WRITER_CLUSTER_D_TOKEN}"
    url_map:
      - src_paths:
          - "/api/v1/write"
        headers:
          - "Authorization:"
        url_prefix: "http://victoriametrics:8428/?extra_label=cluster=cluster-d"
  - name: grafana-reader
    username: "%{GRAFANA_USERNAME}"
    password: "%{GRAFANA_PASSWORD}"
    url_map:
      - src_paths:
          - "/api/v1/query"
          - "/api/v1/query_range"
          - "/api/v1/series"
          - "/api/v1/labels"
          - "/api/v1/label/[^/]+/values"
          - "/api/v1/metadata"
          - "/api/v1/status/buildinfo"
        headers:
          - "Authorization:"
        url_prefix: "http://victoriametrics:8428/"
  - name: management-telemetry-reader
    bearer_token: "%{TELEMETRY_TOKEN}"
    url_map:
      - src_paths:
          - "/telemetry/victoriametrics/metrics"
        drop_src_path_prefix_parts: 2
        headers:
          - "Authorization:"
        url_prefix: "http://victoriametrics:8428/"
      - src_paths:
          - "/telemetry/vmauth/metrics"
        drop_src_path_prefix_parts: 2
        headers:
          - "Authorization:"
        url_prefix: "http://127.0.0.1:8426/"
