---
apiVersion: builtin
kind: SecretGenerator
metadata:
  name: longhorn-backup-secret-azure
behavior: create
options:
  disableNameSuffixHash: true
  labels:
    kustomize-base: overlay
envs:
  - ./secrets/secret-azure-backup-store.env
