# =============================================================================
# Mailrise Configuration File
# Mailrise Container
# https://github.com/YoRyan/mailrise
# -----------------------------------------------------------------------------
# Developer.......: Andre Essing (https://github.com/aessing)
#                                (https://www.linkedin.com/in/aessing/)
# -----------------------------------------------------------------------------
# THIS CODE AND INFORMATION ARE PROVIDED "AS IS" WITHOUT WARRANTY OF ANY KIND,
# EITHER EXPRESSED OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE IMPLIED
# WARRANTIES OF MERCHANTABILITY AND/OR FITNESS FOR A PARTICULAR PURPOSE.
# =============================================================================

listen:
  port: 465

tls:
  mode: starttls
  certfile: /etc/mailrise/cert/tls.crt
  keyfile: /etc/mailrise/cert/tls.key

# =============================================================================

smtp:
  hostname: 'mailrise.sample.com'
  auth:
    basic:
      user01: !env_var MAILRISE_USR_USER01
      user02: !env_var MAILRISE_USR_USER02

# =============================================================================

configs:
  admins@sample.com:
    urls:
      - !env_var MAILRISE_SVC_SERVICE01_URL
      - !env_var MAILRISE_SVC_SERVICE02_URL

  service01@sample.com:
    urls:
      - !env_var MAILRISE_SVC_SERVICE01_URL

  service02@sample.com:
    urls:
      - !env_var MAILRISE_SVC_SERVICE01_URL
