---
apiVersion: builtin
kind: ConfigMapGenerator
metadata:
  name: alloy-unpoller-environment
behavior: create
options:
  labels:
    app.kubernetes.io/component: collector
  annotations:
    reloader.stakater.com/match: 'false'
envs:
  - ./configs/alloy.env
