apiVersion: 1
datasources:
  - name: Home Assistant HistoryDB
    uid: home-assistant-historydb
    type: prometheus
    access: proxy
    url: https://history.example.com
    basicAuth: true
    basicAuthUser: $HA_HISTORYDB_USERNAME
    secureJsonData:
      basicAuthPassword: $HA_HISTORYDB_PASSWORD
    jsonData:
      httpMethod: POST
      timeInterval: 15s
      queryTimeout: 60s
      tlsSkipVerify: false
    editable: false
    isDefault: false
