---
apiVersion: v1
kind: Service
metadata:
  name: grafana-haengine
  labels:
    app.kubernetes.io/component: 'haengine'
spec:
  selector:
    app.kubernetes.io/component: 'haengine'
  ports:
    - protocol: TCP
      port: 6379
      targetPort: 6379
      name: redis
  type: ClusterIP
