---
apiVersion: builtin
kind: SecretGenerator
metadata:
  name: monitoring-agent-uptimekuma-database
behavior: create
options:
  labels:
    app.kubernetes.io/component: alloy
  annotations:
    reloader.stakater.com/match: 'false'
type: Opaque
envs:
  - ./secrets/secret-monitoring-agent-uptimekuma-database.env
