---
apiVersion: builtin
kind: SecretGenerator
metadata:
  name: postgres-database-user-app01
behavior: create
options:
  disableNameSuffixHash: true
  labels:
    app.kubernetes.io/component: 'database'
    cnpg.io/reload: 'true'
  annotations:
    reloader.stakater.com/match: 'false'
    reloader.stakater.com/ignore: 'true'
type: kubernetes.io/basic-auth
envs:
  - ./databases/secret-app01.env
---
apiVersion: builtin
kind: SecretGenerator
metadata:
  name: postgres-database-user-app02
behavior: create
options:
  disableNameSuffixHash: true
  labels:
    app.kubernetes.io/component: 'database'
    cnpg.io/reload: 'true'
  annotations:
    reloader.stakater.com/match: 'false'
    reloader.stakater.com/ignore: 'true'
type: kubernetes.io/basic-auth
envs:
  - ./databases/secret-app02.env
