---
apiVersion: builtin
kind: ConfigMapGenerator
metadata:
  name: grafana-monitoring-logs-datasource
behavior: create
options:
  labels:
    app.kubernetes.io/component: application
  annotations:
    reloader.stakater.com/match: 'false'
files:
  - monitoring-logs.yaml=./configs/monitoring-logs.yaml
