---
apiVersion: builtin
kind: SecretGenerator
metadata:
  name: grafana-smtp
behavior: create
options:
  labels:
    app.kubernetes.io/component: 'application'
type: Opaque
envs:
  - ./secrets/secret-grafana-smtp.env
