---
apiVersion: builtin
kind: SecretGenerator
metadata:
  name: grafana-database-user
behavior: create
options:
  disableNameSuffixHash: true
  labels:
    app.kubernetes.io/component: 'database'
    cnpg.io/reload: "true"
type: kubernetes.io/basic-auth
envs:
  - ./secrets/secret-grafana-database-user.env
