---
apiVersion: builtin
kind: SecretGenerator
metadata:
  name: grafana-renderer-auth
behavior: create
options:
  labels:
    app.kubernetes.io/component: 'renderer'
type: Opaque
envs:
  - ./secrets/secret-grafana-renderer-auth.env
