---
apiVersion: builtin
kind: SecretGenerator
metadata:
  name: grafana-database-objectstore
behavior: create
options:
  disableNameSuffixHash: true
  labels:
    app.kubernetes.io/component: 'database'
    cnpg.io/reload: "true"
type: Opaque
envs:
  - ./secrets/secret-grafana-database-objectstore.env
