---
apiVersion: builtin
kind: SecretGenerator
metadata:
  name: grafana-haengine-auth
behavior: create
options:
  labels:
    app.kubernetes.io/component: 'haengine'
type: Opaque
envs:
  - ./secrets/secret-grafana-haengine-auth.env
