---
apiVersion: builtin
kind: SecretGenerator
metadata:
  name: grafana-monitoring-logs-datasource
behavior: create
options:
  labels:
    app.kubernetes.io/component: application
  annotations:
    reloader.stakater.com/match: 'false'
type: Opaque
envs:
  - ./secrets/secret-grafana-monitoring-logs-datasource.env
