---
apiVersion: builtin
kind: SecretGenerator
metadata:
  name: grafana-home-assistant-historydb-datasource
behavior: create
options:
  labels:
    app.kubernetes.io/component: application
  annotations:
    # The generated name suffix triggers a Grafana rollout after rotation.
    reloader.stakater.com/match: 'false'
type: Opaque
envs:
  - ./secrets/secret-grafana-home-assistant-historydb-datasource.env
