---
apiVersion: builtin
kind: SecretGenerator
metadata:
  name: grafana-metrics
behavior: create
options:
  labels:
    app.kubernetes.io/component: 'application'
type: Opaque
envs:
  - ./secrets/secret-grafana-metrics.env
