---
apiVersion: builtin
kind: SecretGenerator
metadata:
  name: grafana-secretkey
behavior: create
options:
  labels:
    app.kubernetes.io/component: 'application'
type: Opaque
envs:
  - ./secrets/secret-grafana-secretkey.env
