---
apiVersion: builtin
kind: ConfigMapGenerator
metadata:
  name: grafana-renderer-config
behavior: create
options:
  labels:
    app.kubernetes.io/component: 'renderer' # The component within the architecture
files:
  - ./configs/config.json
