---
apiVersion: helm.cattle.io/v1
kind: HelmChartConfig
metadata:
  name: authentik
spec:
  valuesContent: |-
    ---
    global:
      deploymentAnnotations:
        reloader.stakater.com/search: 'true'  # Enables search mode (only reloads if matching secrets/configMaps are found)
        reloader.stakater.com/rollout-strategy: 'rollout'  # Specifies the rollout strategy for the workload (rollout (default) / restart)
      secretAnnotations:
        reloader.stakater.com/match: 'true'
        reloader.stakater.com/ignore: 'false'
      env:
        - name: AUTHENTIK_LISTEN__HTTP
          value: 0.0.0.0:9000
        - name: AUTHENTIK_LISTEN__HTTPS
          value: 0.0.0.0:9443
        - name: AUTHENTIK_LISTEN__METRICS
          value: 0.0.0.0:9300
        - name: AUTHENTIK_POSTGRESQL__USER
          valueFrom:
            secretKeyRef:
              name: authentik-database-user
              key: username
        - name: AUTHENTIK_POSTGRESQL__PASSWORD
          valueFrom:
            secretKeyRef:
              name: authentik-database-user
              key: password
        - name: AUTHENTIK_POSTGRESQL__READ_REPLICAS__0__USER
          valueFrom:
            secretKeyRef:
              name: authentik-database-user
              key: username
        - name: AUTHENTIK_POSTGRESQL__READ_REPLICAS__0__PASSWORD
          valueFrom:
            secretKeyRef:
              name: authentik-database-user
              key: password
      envFrom:
        - secretRef:
            name: authentik-config

    authentik:
      error_reporting:
        enabled: false
        send_pii: false
      disable_update_check: false
      disable_startup_analytics: true

    server:
      replicas: 2

    worker:
      replicas: 2
