---
apiVersion: builtin
kind: SecretGenerator
metadata:
  name: authentik-config
behavior: create
options:
  disableNameSuffixHash: true
  labels:
    app.kubernetes.io/component: 'application'
  annotations:
    reloader.stakater.com/match: 'true'
    reloader.stakater.com/ignore: 'false'
type: Opaque
envs:
  - ./secrets/secret-authentik-config.env
