---
apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component

namespace: authentik

resources:
  - ./resources/helmchartconfig.yaml
  - ./resources/helmchart.yaml
  - ./resources/certificate.yaml
  - ./resources/ingressroute.yaml

patches:
  # If you change target-namespace, you must change the namespace above
  - path: ./patches/target-namespace.yaml
    target:
      group: helm.cattle.io
      version: v1
      kind: HelmChart

transformers:
  # HelmChart and HelmChartConfigs needs to be deployed in namespace kube-system
  - ./transformers/helmchartconfig.yaml
  - ./transformers/helmchart.yaml
