---
apiVersion: builtin
kind: ReplicaCountTransformer
metadata:
  name: nameserver-replicatransformer
replica:
  name: nameserver
  count: 3
fieldSpecs:
  - path: spec/replicas
    create: true
    kind: Deployment
  - path: spec/replicas
    create: true
    kind: ReplicationController
  - path: spec/replicas
    create: true
    kind: ReplicaSet
  - path: spec/replicas
    create: true
    kind: StatefulSet
