apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

sortOptions:
  order: fifo

buildMetadata:
  - managedByLabel
  - originAnnotations
  # - transformerAnnotations

resources:
  - ../../base

components:
  - ../../components/_database
  - ../../components/_application

generators:
  - ./generators/secret-authentik-config.yaml
  - ./generators/secret-authentik-database-objectstore.yaml
  - ./generators/secret-authentik-database-user.yaml

patches:
  # https://github.com/goauthentik/authentik
  - path: ./patches/authentik-database-objectstore.yaml
    target:
      group: barmancloud.cnpg.io
      version: v1
      kind: ObjectStore
      name: authentik-database-objectstore
  - path: ./patches/authentik-database-schedule.yaml
    target:
      group: postgresql.cnpg.io
      version: v1
      kind: ScheduledBackup
      name: authentik-database-scheduledbackup
  - path: ./patches/authentik-database.json
    target:
      group: postgresql.cnpg.io
      version: v1
      kind: Cluster
      name: authentik-database
  - path: ./patches/certificate.json
    target:
      group: cert-manager.io
      version: v1
      kind: Certificate
      name: authentik
  - path: ./patches/ingressroute.json
    target:
      group: traefik.io
      version: v1alpha1
      kind: IngressRoute
  - path: ./patches/version.json
    target:
      group: helm.cattle.io
      version: v1
      kind: HelmChart
  - path: ./patches/helmchartconfig.yaml
    target:
      group: helm.cattle.io
      version: v1
      kind: HelmChartConfig

transformers:
  - ./transformers/labels.yaml
