---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

sortOptions:
  order: fifo

buildMetadata:
  - managedByLabel
  - originAnnotations
  # - transformerAnnotations

resources:
  - ../../base
  - ./resources/certificate-ldap.yaml

components:
  - ../../components/_application

generators:
  - ./generators/secret-authentik-config.yaml
  - ./generators/secret-authentik-database-user.yaml

patches:
  # https://github.com/goauthentik/authentik
  - path: ./patches/certificate.yaml
    target:
      group: cert-manager.io
      version: v1
      kind: Certificate
      name: authentik
  - path: ./patches/ingressroute.yaml
    target:
      group: traefik.io
      version: v1alpha1
      kind: IngressRoute
  - path: ./patches/version.yaml
    target:
      group: helm.cattle.io
      version: v1
      kind: HelmChart
  - path: ./patches/helmchartconfig.yaml
    target:
      group: helm.cattle.io
      version: v1
      kind: HelmChartConfig

transformers:
  - ./transformers/labels.yaml
