apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

sortOptions:
  # If not specified, HelmChart will be deployed before HelmChartConfig - This can lead to unconfigured HelmChart deployments
  order: fifo

buildMetadata:
  - managedByLabel
  - originAnnotations
  # - transformerAnnotations

labels:
  - includeSelectors: false
    pairs:
      app.kubernetes.io/component: ingress-controller
      app.kubernetes.io/instance: traefik
      app.kubernetes.io/name: traefik
      app.kubernetes.io/part-of: system-services

resources:
  - ../../base
  - ./resources/middleware-dashboard-auth.yaml

generators:
  - ./generators/secret-dashboard-auth.yaml

patches:
  # https://github.com/traefik/traefik
  # https://github.com/traefik/traefik-helm-chart
  - path: ./patches/version.json
    target:
      group: helm.cattle.io
      version: v1
      kind: HelmChart
  - path: ./patches/certificate-dashboard.json
    target:
      group: cert-manager.io
      version: v1
      kind: Certificate
  - path: ./patches/helmchartconfig.yaml
    target:
      group: helm.cattle.io
      version: v1
      kind: HelmChartConfig
  - path: ./patches/ingressroute-dashboard.json
    target:
      group: traefik.io
      version: v1alpha1
      kind: IngressRoute
  - path: ./patches/namespace.json
    target:
      name: traefik-dashboard-basicauth
